import { NextRequest, NextResponse } from 'next/server';
import { supabaseAdmin } from '@/lib/supabase-admin';
import { requireCommitteeAccess, hasPermission } from '@/middleware/auth';
import { validateRequestBody, whatsAppRequestReviewSchema } from '@/lib/validation';
import { createPostgradAccessToken } from '@/lib/postgrad-access-tokens';
import { sendResendEmail } from '@/lib/resend';

async function authorised(request: NextRequest) { const result = await requireCommitteeAccess(request); if (!result.success) return result; if (!hasPermission(result.data.permissions, 'manage-postgrad-whatsapp')) return { success: false as const, response: NextResponse.json({ error: 'You do not have permission to manage the Postgraduate WhatsApp group' }, { status: 403 }) }; return result; }
async function sendApprovalEmail(email: string, firstName: string) { const result = await createPostgradAccessToken(email, 'manual_approval'); if (!result.token) return false; const url = `${process.env.NEXT_PUBLIC_BASE_URL || 'http://localhost:3000'}/postgrad-join#${result.token}`; return sendResendEmail({ to: email, from: process.env.RESEND_FROM_EMAIL || 'UMHC Hiking Club <response@mail.umhc.org.uk>', subject: 'UMHC Postgraduate WhatsApp Group Access Approved', html: `<p>Hi ${firstName},</p><p>Your request to join the UMHC Postgraduate WhatsApp group has been approved.</p><p><a href="${url}">Join the Postgraduate WhatsApp group</a></p><p>This link is valid for 24 hours and can only be used once.</p>` }); }
export async function GET(request: NextRequest) { const auth = await authorised(request); if (!auth.success) return auth.response; const { data, error } = await supabaseAdmin.schema('whatsapp_security').from('postgrad_requests').select('*').order('created_at', { ascending: false }); if (error?.code === '42P01') return NextResponse.json({ success: true, requests: [], setupWarning: 'postgrad_requests table not found. Run the Postgraduate WhatsApp migration.' }); if (error) return NextResponse.json({ error: 'Failed to fetch requests', details: error.message }, { status: 500 }); return NextResponse.json({ success: true, requests: data || [] }); }
export async function PATCH(request: NextRequest) { const auth = await authorised(request); if (!auth.success) return auth.response; const validation = await validateRequestBody(request, whatsAppRequestReviewSchema); if (!validation.success) return NextResponse.json({ error: validation.error }, { status: 400 }); const { requestId, action, reviewedBy } = validation.data; const { data, error: fetchError } = await supabaseAdmin.schema('whatsapp_security').from('postgrad_requests').select('*').eq('id', requestId).single(); if (fetchError || !data) return NextResponse.json({ error: 'Request not found' }, { status: 404 }); const { error } = await supabaseAdmin.schema('whatsapp_security').from('postgrad_requests').update({ status: action === 'approve' ? 'approved' : 'rejected', reviewed_by: reviewedBy, reviewed_at: new Date().toISOString() }).eq('id', requestId); if (error) return NextResponse.json({ error: 'Failed to update request' }, { status: 500 }); if (action === 'approve' && !(await sendApprovalEmail(data.email, data.first_name))) return NextResponse.json({ success: true, warning: 'Request approved, but the email could not be sent.' }); return NextResponse.json({ success: true, message: `Request ${action}d successfully` }); }
export async function POST() { return NextResponse.json({ error: 'Method not allowed' }, { status: 405 }); }