'use client';

import { useEffect, useState } from 'react';

interface RequestRow { id: string; first_name: string; surname: string; email: string; phone: string; status: string; created_at: string; }
interface Props { user?: { email: string | null; given_name: string | null; family_name: string | null } }

export default function PostgradWhatsAppConsole({ user }: Props) {
  const [link, setLink] = useState(''); const [requests, setRequests] = useState<RequestRow[]>([]); const [message, setMessage] = useState(''); const [linkMessage, setLinkMessage] = useState(''); const [savingLink, setSavingLink] = useState(false); const [loading, setLoading] = useState(true);
  async function load() { setLoading(true); const [config, requestData] = await Promise.all([fetch('/api/committee/postgrad-whatsapp-config'), fetch('/api/committee/postgrad-whatsapp-requests')]); const configJson = await config.json(); const requestJson = await requestData.json(); setLink(configJson.config?.whatsapp_postgrad_link || ''); setRequests(requestJson.requests || []); setMessage(requestJson.setupWarning || ''); setLoading(false); }
  useEffect(() => { load(); }, []);
  async function updateLink() { setSavingLink(true); setLinkMessage(''); try { const response = await fetch('/api/committee/postgrad-whatsapp-config', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ whatsapp_postgrad_link: link }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Failed to update the postgraduate WhatsApp link.'); setLinkMessage(data.message || 'Postgraduate WhatsApp link updated successfully.'); } catch (error) { setLinkMessage(error instanceof Error ? error.message : 'Failed to update the postgraduate WhatsApp link.'); } finally { setSavingLink(false); } }
  async function review(id: string, action: 'approve' | 'reject') { const reviewer = `${user?.given_name || ''} ${user?.family_name || ''}`.trim() || user?.email || 'Committee member'; await fetch('/api/committee/postgrad-whatsapp-requests', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ requestId: id, action, reviewedBy: reviewer }) }); await load(); }
  if (loading) return <p className="p-8 text-slate-grey">Loading Postgraduate console...</p>;
  return <div className="space-y-8 font-sans"><div className="rounded-lg border border-gray-200 bg-cream-white p-6"><h2 className="text-xl font-semibold text-deep-black">Postgraduate group link</h2><div className="mt-4 flex flex-col gap-3 sm:flex-row"><input className="min-w-0 flex-1 rounded border border-gray-300 p-3" value={link} onChange={(e) => setLink(e.target.value)} aria-label="Postgraduate WhatsApp invite link" /><button className="rounded bg-umhc-green px-4 py-2 font-semibold text-white disabled:opacity-50" onClick={updateLink} disabled={savingLink}>{savingLink ? 'Updating...' : 'Update link'}</button></div>{linkMessage && <p className="mt-3 text-sm text-slate-grey" role="status">{linkMessage}</p>}</div><div className="rounded-lg border border-gray-200 bg-cream-white p-6"><h2 className="text-xl font-semibold text-deep-black">Manual access requests ({requests.filter((request) => request.status === 'pending').length} pending)</h2>{message && <p className="mt-3 text-slate-grey" role="status">{message}</p>}<div className="mt-4 space-y-3">{requests.length === 0 ? <p className="text-slate-grey">No requests found.</p> : requests.map((request) => <div className="flex flex-col gap-3 rounded border border-gray-200 bg-white p-4 sm:flex-row sm:items-center sm:justify-between" key={request.id}><div><p className="font-semibold">{request.first_name} {request.surname}</p><p className="text-sm text-slate-grey">{request.email} · {request.phone}</p><p className="text-xs uppercase text-slate-grey">{request.status}</p></div>{request.status === 'pending' && <div className="flex gap-2"><button className="rounded bg-green-600 px-3 py-2 text-sm font-semibold text-white" onClick={() => review(request.id, 'approve')}>Approve</button><button className="rounded bg-red-600 px-3 py-2 text-sm font-semibold text-white" onClick={() => review(request.id, 'reject')}>Reject</button></div>}</div>)}</div></div></div>;
}