'use client';

import { FormEvent, useEffect, useState } from 'react';
import { isValidPhoneNumber } from 'libphonenumber-js';

export default function PostgradVerificationForm() {
  const [email, setEmail] = useState(''); const [phone, setPhone] = useState(''); const [terms, setTerms] = useState(false); const [captcha, setCaptcha] = useState(''); const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [busy, setBusy] = useState(false);
  useEffect(() => { const script = document.createElement('script'); script.src = 'https://challenges.cloudflare.com/turnstile/v0/api.js'; script.async = true; script.onload = () => { if (window.turnstile) window.turnstile.render('#postgrad-turnstile', { sitekey: '0x4AAAAAABjQtmXdSHD15CPT', callback: setCaptcha, 'error-callback': () => setCaptcha(''), 'expired-callback': () => setCaptcha('') }); }; document.head.appendChild(script); return () => script.remove(); }, []);
  async function submit(event: FormEvent) { event.preventDefault(); setError(''); setSuccess(''); const emailParts = email.toLowerCase().split('@'); if (emailParts.length !== 2 || (emailParts[1] !== 'ac.uk' && !emailParts[1].endsWith('.ac.uk'))) { setError('Automatic access requires a university email address ending in .ac.uk. International or other non-.ac.uk postgraduate students can request manual access.'); return; } if (!isValidPhoneNumber(phone)) { setError('Please enter a valid phone number with country code.'); return; } if (!terms || !captcha) { setError('Please accept the terms and complete the security check.'); return; } setBusy(true); try { const response = await fetch('/api/postgrad-whatsapp-simplified', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email, phone, turnstileToken: captcha }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setSuccess('A verification link has been sent to your postgraduate university email address.'); setEmail(''); setPhone(''); } catch (err) { setError(err instanceof Error ? err.message : 'Verification failed.'); } finally { setBusy(false); } }
  return <section className="w-full max-w-lg font-sans"><h1 className="text-3xl sm:text-4xl font-semibold text-deep-black text-center">Join the Postgraduate Community</h1><p className="mt-3 text-center text-slate-grey">Use your postgraduate university email to get access to the UMHC Postgraduate WhatsApp group. If you don&apos;t have access to it, you can <a className="text-umhc-green underline" href="/postgrad-whatsapp-request">request access manually</a>.</p><form onSubmit={submit} className="mt-8 space-y-5" aria-label="Postgraduate WhatsApp verification form"><label className="block text-sm font-medium">Postgraduate university email<input className="mt-1 w-full rounded-lg border-2 border-gray-200 bg-cream-white p-3" type="email" required value={email} onChange={(e) => setEmail(e.target.value)} placeholder="firstname.lastname@postgrad.manchester.ac.uk" /><span className="mt-1 block text-xs font-normal text-slate-grey">Most UoM postgrad email addresses end in @postgrad.manchester.ac.uk</span></label><label className="block text-sm font-medium">Phone number<input className="mt-1 w-full rounded-lg border-2 border-gray-200 bg-cream-white p-3" type="tel" required value={phone} onChange={(e) => setPhone(e.target.value)} placeholder="+44 7123 456 789" /><span className="mt-1 block text-xs font-normal text-slate-grey">Enter the phone number with the country code (e.g., +44 for UK, +1 for US) that you will be using to join the WhatsApp Community with. This helps us verify WhatsApp group members.</span></label><label className="flex items-start gap-3 text-sm"><input className="mt-0.5 h-5 w-5 shrink-0" type="checkbox" checked={terms} onChange={(e) => setTerms(e.target.checked)} />I agree to the <a className="text-umhc-green underline" href="/terms">Terms of Service and Privacy Policy</a>.</label><div id="postgrad-turnstile" className="min-h-[78px] flex justify-center" />{error && <p className="text-red-700" role="alert">{error}</p>}{success && <p className="text-green-700" role="status">{success}</p>}<button className="w-full rounded-lg bg-umhc-green px-5 py-3 font-semibold text-white disabled:opacity-50" disabled={busy} type="submit">{busy ? 'Sending...' : 'Email me a join link'}</button></form></section>;
}