'use client';

import { FormEvent, useEffect, useState } from 'react';
import { isValidPhoneNumber } from 'libphonenumber-js';

export default function PostgradManualRequestForm() {
  const [fields, setFields] = useState({ firstName: '', surname: '', email: '', phone: '', trips: '' }); const [terms, setTerms] = useState(false); const [captcha, setCaptcha] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  useEffect(() => { const script = document.createElement('script'); script.src = 'https://challenges.cloudflare.com/turnstile/v0/api.js'; script.async = true; script.onload = () => { if (window.turnstile) window.turnstile.render('#postgrad-request-turnstile', { sitekey: '0x4AAAAAABjQtmXdSHD15CPT', callback: setCaptcha, 'error-callback': () => setCaptcha(''), 'expired-callback': () => setCaptcha('') }); }; document.head.appendChild(script); return () => script.remove(); }, []);
  const update = (key: keyof typeof fields, value: string) => setFields((current) => ({ ...current, [key]: value }));
  async function submit(event: FormEvent) { event.preventDefault(); setMessage(''); if (!fields.firstName || !fields.surname || !fields.email || !isValidPhoneNumber(fields.phone)) { setMessage('Please complete all required fields with valid details.'); return; } if (!terms || !captcha) { setMessage('Please accept the terms and complete the security check.'); return; } setBusy(true); try { const response = await fetch('/api/postgrad-whatsapp-request', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...fields, userType: 'other', turnstileToken: captcha }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setMessage('Your request has been submitted. The committee will review it and email you.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Request failed.'); } finally { setBusy(false); } }
  return <section className="w-full max-w-lg font-sans"><h1 className="text-3xl sm:text-4xl font-semibold text-deep-black text-center">Request Postgraduate WhatsApp Access</h1><p className="mt-3 text-center text-slate-grey">A committee member will review your request to join the UMHC Postgraduate WhatsApp group. Use this form if you study at a non-UK university, do not have a <strong>.ac.uk</strong> address, or need access with another postgraduate email format.</p><form onSubmit={submit} className="mt-8 space-y-4" aria-label="Postgraduate WhatsApp manual access request form">{(['firstName', 'surname', 'email', 'phone'] as const).map((key) => <label key={key} className="block text-sm font-medium">{key === 'firstName' ? 'First name' : key === 'surname' ? 'Surname' : key === 'email' ? 'Email address' : 'Phone number'}<input className="mt-1 w-full rounded-lg border-2 border-gray-200 bg-cream-white p-3" required type={key === 'email' ? 'email' : key === 'phone' ? 'tel' : 'text'} value={fields[key]} onChange={(e) => update(key, e.target.value)} placeholder={key === 'firstName' ? 'John' : key === 'surname' ? 'Smith' : key === 'email' ? 'your.email@example.com' : '+44 7123 456 789'} /></label>)}<label className="block text-sm font-medium">Relevant hiking experience<textarea className="mt-1 w-full rounded-lg border-2 border-gray-200 bg-cream-white p-3" rows={3} value={fields.trips} onChange={(e) => update('trips', e.target.value)} placeholder="e.g. Hiked with some friends in the Peak District last summer, went on the Snowdon trip with UMHC in September..." /></label><label className="flex items-start gap-3 text-sm"><input className="mt-0.5 h-5 w-5 shrink-0" type="checkbox" checked={terms} onChange={(e) => setTerms(e.target.checked)} />I agree to the <a className="text-umhc-green underline" href="/terms">Terms of Service and Privacy Policy</a>.</label><div id="postgrad-request-turnstile" className="min-h-[78px] flex justify-center" />{message && <p className="text-slate-grey" role="status">{message}</p>}<button className="w-full rounded-lg bg-umhc-green px-5 py-3 font-semibold text-white disabled:opacity-50" disabled={busy} type="submit">{busy ? 'Submitting...' : 'Submit request'}</button></form></section>;
}